### ISSUE TITLE
Resolve mongodb issue

### ISSUE THREAD

**Issue by torrinworx** [torrinworx/Bitorch#3]
An issue is occurring with monogdb operations in  /backend/utils/mongo.py after the main.py file has already made the connection to the db:
```
2024-01-26 19:18:48 ERROR:    Exception in ASGI application
2024-01-26 19:18:48   + Exception Group Traceback (most recent call last):
2024-01-26 19:18:48   |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/_utils.py", line 85, in collapse_excgroups
2024-01-26 19:18:48   |     yield
2024-01-26 19:18:48   |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 190, in __call__
2024-01-26 19:18:48   |     async with anyio.create_task_group() as task_group:
2024-01-26 19:18:48   |   File "/Bitorch/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
2024-01-26 19:18:48   |     raise BaseExceptionGroup(
2024-01-26 19:18:48   | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
2024-01-26 19:18:48   +-+---------------- 1 ----------------
2024-01-26 19:18:48     | Traceback (most recent call last):
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-01-26 19:18:48     |     result = await app(  # type: ignore[func-returns-value]
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-01-26 19:18:48     |     return await self.app(scope, receive, send)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-01-26 19:18:48     |     await super().__call__(scope, receive, send)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-01-26 19:18:48     |     await self.middleware_stack(scope, receive, send)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-01-26 19:18:48     |     raise exc
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-01-26 19:18:48     |     await self.app(scope, receive, _send)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-01-26 19:18:48     |     await self.app(scope, receive, send)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-01-26 19:18:48     |     with collapse_excgroups():
2024-01-26 19:18:48     |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-01-26 19:18:48     |     self.gen.throw(typ, value, traceback)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/_utils.py", line 91, in collapse_excgroups
2024-01-26 19:18:48     |     raise exc
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 192, in __call__
2024-01-26 19:18:48     |     await response(scope, wrapped_receive, send)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/responses.py", line 158, in __call__
2024-01-26 19:18:48     |     await self.background()
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/background.py", line 26, in __call__
2024-01-26 19:18:48     |     await self.func(*self.args, **self.kwargs)
2024-01-26 19:18:48     |   File "/Bitorch/backend/middleware/request_logger.py", line 68, in update_peer_history
2024-01-26 19:18:48     |     await PexMongo.update_peer_request_history(
2024-01-26 19:18:48     |   File "/Bitorch/backend/api/pex/pex_mongo.py", line 118, in update_peer_request_history
2024-01-26 19:18:48     |     peer_exists = await mongo_manager.find_documents(collection_name, peer_dict)
2024-01-26 19:18:48     |   File "/Bitorch/backend/utils/mongo.py", line 49, in find_documents
2024-01-26 19:18:48     |     documents = [doc async for doc in cursor]
2024-01-26 19:18:48     |   File "/Bitorch/backend/utils/mongo.py", line 49, in <listcomp>
2024-01-26 19:18:48     |     documents = [doc async for doc in cursor]
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/motor/core.py", line 1412, in next
2024-01-26 19:18:48     |     if self.alive and (self._buffer_size() or await self._get_more()):
2024-01-26 19:18:48     |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-01-26 19:18:48     |     result = self.fn(*self.args, **self.kwargs)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/cursor.py", line 1155, in _refresh
2024-01-26 19:18:48     |     self.__session = self.__collection.database.client._ensure_session()
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1823, in _ensure_session
2024-01-26 19:18:48     |     return self.__start_session(True, causal_consistency=False)
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
2024-01-26 19:18:48     |     self._topology._check_implicit_session_support()
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 573, in _check_implicit_session_support
2024-01-26 19:18:48     |     self._check_session_support()
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 589, in _check_session_support
2024-01-26 19:18:48     |     self._select_servers_loop(
2024-01-26 19:18:48     |   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 259, in _select_servers_loop
2024-01-26 19:18:48     |     raise ServerSelectionTimeoutError(
2024-01-26 19:18:48     | pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65b44b9e0dafcc490b520830, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-01-26 19:18:48     +------------------------------------
2024-01-26 19:18:48 
2024-01-26 19:18:48 During handling of the above exception, another exception occurred:
2024-01-26 19:18:48 
2024-01-26 19:18:48 Traceback (most recent call last):
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
2024-01-26 19:18:48     result = await app(  # type: ignore[func-returns-value]
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-01-26 19:18:48     return await self.app(scope, receive, send)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-01-26 19:18:48     await super().__call__(scope, receive, send)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-01-26 19:18:48     await self.middleware_stack(scope, receive, send)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-01-26 19:18:48     raise exc
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-01-26 19:18:48     await self.app(scope, receive, _send)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
2024-01-26 19:18:48     await self.app(scope, receive, send)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
2024-01-26 19:18:48     with collapse_excgroups():
2024-01-26 19:18:48   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-01-26 19:18:48     self.gen.throw(typ, value, traceback)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/_utils.py", line 91, in collapse_excgroups
2024-01-26 19:18:48     raise exc
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 192, in __call__
2024-01-26 19:18:48     await response(scope, wrapped_receive, send)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/responses.py", line 158, in __call__
2024-01-26 19:18:48     await self.background()
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/starlette/background.py", line 26, in __call__
2024-01-26 19:18:48     await self.func(*self.args, **self.kwargs)
2024-01-26 19:18:48   File "/Bitorch/backend/middleware/request_logger.py", line 68, in update_peer_history
2024-01-26 19:18:48     await PexMongo.update_peer_request_history(
2024-01-26 19:18:48   File "/Bitorch/backend/api/pex/pex_mongo.py", line 118, in update_peer_request_history
2024-01-26 19:18:48     peer_exists = await mongo_manager.find_documents(collection_name, peer_dict)
2024-01-26 19:18:48   File "/Bitorch/backend/utils/mongo.py", line 49, in find_documents
2024-01-26 19:18:48     documents = [doc async for doc in cursor]
2024-01-26 19:18:48   File "/Bitorch/backend/utils/mongo.py", line 49, in <listcomp>
2024-01-26 19:18:48     documents = [doc async for doc in cursor]
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/motor/core.py", line 1412, in next
2024-01-26 19:18:48     if self.alive and (self._buffer_size() or await self._get_more()):
2024-01-26 19:18:48   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-01-26 19:18:48     result = self.fn(*self.args, **self.kwargs)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/cursor.py", line 1155, in _refresh
2024-01-26 19:18:48     self.__session = self.__collection.database.client._ensure_session()
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1823, in _ensure_session
2024-01-26 19:18:48     return self.__start_session(True, causal_consistency=False)
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
2024-01-26 19:18:48     self._topology._check_implicit_session_support()
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 573, in _check_implicit_session_support
2024-01-26 19:18:48     self._check_session_support()
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 589, in _check_session_support
2024-01-26 19:18:48     self._select_servers_loop(
2024-01-26 19:18:48   File "/Bitorch/.venv/lib/python3.10/site-packages/pymongo/topology.py", line 259, in _select_servers_loop
2024-01-26 19:18:48     raise ServerSelectionTimeoutError(
2024-01-26 19:18:48 pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 65b44b9e0dafcc490b520830, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
```

A better approach to the singleton pattern we have for MongoDBManager would just to make it procedural and self contained for the operations whenever an endpoint makes a call to the manager.

**Comment by torrinworx** [comment]
Fixed
